/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118034-gd21134313f-20241209"
#endif /* AVUTIL_FFVERSION_H */
